
services:
  postgres:
    image: postgres:15
    container_name: p10_postgres
    restart: always
    environment:
      POSTGRES_USER: p10user
      POSTGRES_PASSWORD: p10pass
      POSTGRES_DB: p10db_dev       # La base `dev` est créée automatiquement
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    container_name: p10_backend
    restart: always
    env_file:
      - ./backend/.env.dev
    depends_on:
      - postgres
    working_dir: /usr/src/app
    ports:
      - '3001:3000'
    command: sh -c "npx prisma migrate deploy && npm run start:prod"


  frontend:
    build: ./frontend
    container_name: p10_frontend
    restart: always
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/.next
    working_dir: /app
    ports:
      - '3000:3000'

volumes:
  pgdata:
  backend-data:

